### PR TITLE
Fix $CI expanstion

### PR DESCRIPTION
**Pull request by Kubuxu**
Yes, the change to `go.mod` is intentional. It is `go mod tidy`.

### CODE REVIEW

**Review by laser — APPROVED** [review]
Sounds good. Looks good.

**Comment by Kubuxu** [comment]
There is I think an unrelated issue on darvin.

**Comment by laser** [comment]
This is true. I have filed a CircleCI support ticket for this issue.

**Comment by Kubuxu** [comment]
Not relevant anymore.

**Pull request closed without merging**
