### PR TITLE
Always pass valid Fr bytes

### PR DESCRIPTION
**Pull request by whyrusleeping**
This feels like a weird way to fix the problem, but i don't know what the 'right' way is

### CODE REVIEW

**Comment by porcuquine** [comment]
I think that we previously specified that these kinds of values (randomness, prover ID, etc.) were defined to be 31 bytes, exactly to avoid this issue. My best recollection is that this was confusing to people (I cannot say who because I don't remember), so for apparently simplicity we standardized on having the 'size' be 32 bytes. The 'true usable size' is 254 bits, so 31 bytes was safe/conservative, while 32 bytes is closer to accurate but in a dangerous way.

The right answer is probably to return to 31 bytes, since that allows the caller to know that all bits provided will be used. (I could imagine this mattering in the case of IDs which — conceptually, even if not in practice — might be sparse in such a way that it would be problematic if they were secretly truncated in the wrong way.)

Alternately, rust-fil-proofs can (and probably should) perform this truncation itself. (I thought it did, but if so this PR would probably be unnecessary?) I still prefer specifying 31 bytes, for the reason given above. cc: @dignifiedquire

**Comment by laser** [comment]
@porcuquine @dignifiedquire 

> I still prefer specifying 31 bytes, for the reason given above. cc: @dignifiedquire

Yeah, I think that's the best approach. My man @dignifiedquire will need to change [a bunch of types in rust-fil-proofs](https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/src/types/mod.rs#L26). Once that's done, I can update the relevant FFI codes and will make PRs into specs-actors.

**Comment by dignifiedquire** [comment]
from slack: 

> @whyrusleeping i'm not sure what the right API here is, but to me, the most ergonomic is passing 32 bytes and having rust zero out the last 2 bits

**Comment by dignifiedquire** [comment]
I don't have a strong preference in either direction, just let me know what you want

**Review by magik6k — APPROVED** [review]
Verified to work in lotus

**Pull request merged**
